create table STDRONE(
	ID INT,
    LONGITUDE DOUBLE NOT NULL , 
    LATITUDE DOUBLE NOT NULL,
    BAROX FLOAT NOT NULL,
    BAROY FLOAT NOT NULL, 
	BAROZ FLOAT NOT NULL, 
    BAROC FLOAT NOT NULL, 
    DTHR DATETIME  NOT NULL
);